version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn backend.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: rq worker scans
    volumes:
      - .:/app
    working_dir: /app
    environment:
      REDIS_HOST: redis
      PYTHONPATH: /app
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
