version: "3.9"
services:
  api:
    build: .
    container_name: cyberai_api
    command: python -m backend.server
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: .
    container_name: cyberai_worker
    command: python -m backend.worker
    volumes:
      - ./results:/app/results
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: cyberai_redis
    ports:
      - "6379:6379"
